import {
  Alessandra,
  Amarildo,
  Andre,
  Basilia,
  Capel,
  Claudia,
  Edileide,
  Emily,
  Flavia,
  Hugo,
  Isabel,
  Jeane,
  Kellen,
  KellyCristina,
  MariaImaculada,
  Michelle,
  Mirelly,
  NadiaCordeiro,
  Nara,
  Natalia,
  Natalina,
  Sabrina,
  Samira,
  Severino,
  Simone,
  Socorro,
  Stefany,
  Vania,
  Vitoria,
} from "../assets/img/Pioneiros";
import {
  capaAlessandra,
  capaAmarildo,
  capaAndre,
  capaBasilia,
  capaCapel,
  capaClaudia,
  capaEdileide,
  capaEmily,
  capaFlavia,
  capaHugo,
  capaIsabel,
  capaJeane,
  capaKellen,
  capaKellyCristina,
  capaMariaImaculada,
  capaMichelle,
  capaMirelly,
  capaNadiaCordeiro,
  capaNara,
  capaNatalia,
  capaNatalina,
  capaSabrina,
  capaSamira,
  capaSeverino,
  capaSimone,
  capaSocorro,
  capaStefany,
  capaVania,
  capaVitoria,
} from "../assets/img/PioneirosCapa";
import { IPionner } from "../types/types";

export const pionner :IPionner[] = [
  {
    id: 1,
    img: Socorro,
    capa: capaSocorro,
    nome: "Socorro",
    batismo: "1993",
    pioneiro: "1996",
    title:
      "Persistência e Amor: Mantendo o Serviço em Meio a Desafios Familiares",
    biografia:
      "Servi como pioneira teve seus desafios como filhos adolescentes e marido opositor mas conseguiu permanecer no serviço e teve muitas alegrias para ela é um imenso privilégio ser pioneira não se vê sem esse trabalho, ser pioneira da uma grande oportunidade de ajudar outros, o serviço de pioneiro  pra ela é amor a Jeová amor a vc mesmo e amor ao próximo.Ela sente muita alegria ser pioneira ela já viu alguns se chegar até o batismo e até algumas dessas estudantes ser até pioneira junto com ela.Para cumprir seu requisito ela diz que tem que fazer arranjos, cedo no dia no mês e no ano sempre fazer mais a cada mês devido imprevistos que possa surgi.",
  },
  {
    id: 2,
    img: NadiaCordeiro,
    capa: capaNadiaCordeiro,
    nome: "Nádia Cordeiro",
    batismo: "2018",
    pioneiro: "2023",
    title: "Equilibrando Amor Maternal e Dedicação Pioneira",
    biografia:
      "Mãe de três meninas Ester Vitória e Melissa serve como Pioneira regular desde 2023 junto com seu marido Hugo e agora sua filha VitóriaTeve alguns desafios para servir como Pioneira um deles foi quando sua filha ficou doente hospitalizado e consegui também administrar seu tempo na pregação com cuidar de suas filhas pequenas e no que tudo isso envolve.Mas servir como Pioneira Ele trouxe muitas alegrias uma delas é as experiências incríveis na pregação como por exemplo uma moradora que nunca nos atendia, agora nós escuta e também ser Pioneira ajuda a dar um bom exemplo para suas filhas de servir a Jeová.Para cumprir seu requisito ela faz uma programação para estar nos rurais,apoiar o arranjo do carrinho e escrever cartas e Estudos dia de sábado e Campo à tarde.Ser Pioneira para ela é um sentimento de alegria gratidão poder ajudar outros a conhecer a Jeová",
  },
  {
    id: 3,
    img: Simone,
    capa: capaSimone,
    nome: "Simone",
    batismo: "2010",
    pioneiro: "2022",
    title: "Conciliando Trabalho e Pioneirismo com Amor Filial",
    biografia:
      "Mãe dedicada de um filho, Simone trabalha incansavelmente fora de casa para prover e cuidar de sua família.  Em meio às responsabilidades familiares, ela tomou a decisão de se dedicar como pioneira, assumindo o compromisso de compartilhar sua fé e dedicar tempo ao serviço voluntário na promoção das mensagens bíblicas.Quando Simone assinou como pioneira, estava enfrentando o desafio adicional de cuidar de sua mãe, que estava acamada na época.  Apesar das dificuldades, ela encontrou grande alegria e satisfação nesse serviço.  Um dos momentos mais tocantes para Simone foi testemunhar sua mãe, mesmo estando acamada, dedicando-se ao estudo da Bíblia e mantendo uma fé inabalável em Jeová e em Suas promessas.  Mesmo através das limitações físicas, Simone, por meio do Zoom, conseguiu participar de reuniões, celebrar a Ceia do Senhor e acompanhar os congressos e assembléias.  Essas experiências encheram seu coração de alegria e gratidão.Para cumprir seus requisitos como pioneira, Simone estabeleceu uma programação semanal, permitindo uma distribuição equilibrada das atividades, evitando a sensação de corrida para alcançar as metas de horas.Ela destaca que ser pioneira a faz sentir-se imensamente feliz e grata a Jeová por conceder-lhe esse precioso privilégio de servir e impactar vidas por meio da mensagem bíblica.",
  },
  {
    id: 4,
    img: Kellen,
    capa: capaKellen,
    nome: "Kellen",
    batismo: "2001",
    pioneiro: "2023",
    title: "Superando Desafios Familiares para Ser Pioneira",
    biografia:
      "Kellen é mãe de duas crianças e dedicada esposa.  Seu caminho como pioneira foi marcado por desafios, especialmente devido ao equilíbrio entre o trabalho e o cuidado de seus filhos pequenos.  No entanto, com determinação e planejamento cuidadoso, ela tomou a decisão de se tornar pioneira.Entre suas muitas alegrias, destaca-se a satisfação de testemunhar como o trabalho dedicado a Jeová contribui para o progresso e bem-estar de seus filhos.  Kellen estabelece uma programação semanal meticulosa, harmonizando seus esforços com as folgas de seu marido, a fim de conciliar seu serviço pioneiro com as responsabilidades familiares.O compromisso de ser pioneira não apenas enriqueceu seu amor por Jeová, mas também trouxe uma imensa alegria e gratidão ao seu coração.  Kellen enxerga o serviço pioneiro não apenas como uma responsabilidade, mas como uma fonte contínua de felicidade e propósito em sua vida.",
  },
  {
    id: 5,
    img: Natalina,
    capa: capaNatalina,
    nome: "Natalina",
    batismo: "2001",
    pioneiro: "2021",
    title: "Persistência Pioneira em Meio a Desafios e Pandemia",
    biografia:
      "Natalina é uma dedicada serva pioneira que enfrentou diversos desafios ao longo de seu serviço, desde ser uma mãe de uma criança pequena até os impactos da pandemia.  Contudo, sua persistência e fé foram recompensadas quando experimentou a profunda alegria de sentir o apoio oportuno de Jeová.O serviço pioneiro não é apenas uma responsabilidade para Natalina, mas uma fonte constante de satisfação e realização.  Ela encontra alegria em oferecer o seu melhor nesse lindo serviço dedicado a Jeová.  Ser pioneira não é apenas uma escolha, mas um estilo de vida que a preenche de satisfação e propósito.Para cumprir com os requisitos, Natalina estabelece uma programação cuidadosa.  Alguns dias são fixos durante a semana, incluindo sua filha Lara, enquanto outros são dedicados a apoiar atividades rurais e outras responsabilidades, como arranjo das cartas.  Essa abordagem equilibrada reflete seu comprometimento em servir a Jeová de maneira diligente e organizada.A história de Natalina é um testemunho inspirador de como o serviço pioneiro, mesmo diante de desafios, pode ser uma fonte inesgotável de alegria e realização na adoração a Jeová",
  },
  {
    id: 6,
    img: Nara,
    capa: capaNara,
    nome: "Nara",
    batismo: "2015",
    pioneiro: "2023",
    title: "Vencendo Desafios Pessoais para Ser Pioneira",
    biografia:
      "Nara enfrentou diversos desafios ao decidir dedicar-se como pioneira, incluindo o equilíbrio entre o trabalho secular, a responsabilidade de criar filhos sozinha e os ajustes necessários em sua própria vida.  No entanto, a decisão de se tornar pioneira trouxe-lhe imensa alegria, especialmente ao oferecer o seu melhor a Jeová e ao compartilhar, com amor, o conhecimento do Deus verdadeiro para ajudar as pessoas a encontrarem esse caminho.Para Nara, ser pioneira é uma sensação única, proporcionando-lhe o privilégio de dedicar mais tempo a esse serviço incrível que tem o potencial de salvar muitas vidas.  Cumprir com os requisitos do serviço pioneiro exige ajustes, especialmente porque ela também trabalha fora, demandando uma cuidadosa administração de seu tempo para realizar essa importante obra.Ela compartilha suas palavras inspiradoras:'Quando assinei para ser pioneira, experimentei uma sensação incrível, pois sempre senti esse desejo ardente de me dedicar mais a realizar esse trabalho maravilhoso.  Jeová nos promete, em Mateus 6:33, que ao colocarmos o reino em primeiro lugar e buscarmos sua justiça, todas as outras coisas nos serão acrescentadas.  Vejo essa promessa se cumprir a cada dia da minha vida.  Sinto uma enorme gratidão por Ele me proporcionar essa alegria.'",
  },
  {
    id: 7,
    img: Mirelly,
    capa: capaMirelly,
    nome: "Mirelly",
    batismo: "2017",
    pioneiro: "2019",
    title: "Alegria e Satisfação no Pioneirismo Durante a Pandemia",
    biografia:
      "A jornada no serviço de pioneira de Mirelly não foi isenta de desafios, especialmente durante a pandemia.  Enfrentar a realidade de ter assinado como pioneira com muitos alvos, apenas para se ver isolada em casa, foi uma dificuldade que ela enfrentou com coragem.  No entanto, apesar desses obstáculos, Mirelly manteve-se firme, encontrando muitas alegrias ao se sentir mais próxima de Jeová e de sua organização.  Lidar com o serviço pioneiro não apenas a protegeu da ansiedade, mas também a afastou das preocupações pessoais.  Ao dedicar seu tempo às revisitas, serviço de campo e estudos, Mirelly viu sua fé e esperança crescerem.  O serviço pioneiro não é apenas uma responsabilidade, mas uma fonte inigualável de alegria e uma expressão de viver da melhor maneira possível.Para cumprir seus requisitos pioneiros, Mirelly estabelece uma programação semanal, adaptando-se aos imprevistos com determinação e flexibilidade.",
  },
  {
    id: 8,
    img: Natalia,
    capa: capaNatalia,
    nome: "Natalia",
    batismo: "2005",
    pioneiro: "2021",
    title:
      "Enfrentando Desafios Profissionais e Alcançando Alegrias no Pioneirismo",
    biografia:
      "Natalia embarcou na jornada de ser pioneira enfrentando alguns desafios significativos, como a distância entre seu trabalho secular e sua casa.  No entanto, as bênçãos de Jeová se manifestaram, permitindo-lhe mudar para um emprego mais próximo, otimizando assim seu tempo para o serviço pioneiro.Atualmente, a continuidade no serviço traz inúmeras alegrias a Natalia.  Participar ativamente no campo, nos estudos e em várias atividades do ministério tornou-se um apoio valioso em sua vida, auxiliando-a no enfrentamento da ansiedade e da depressão que ela enfrentou.  O contato constante com os irmãos e as atividades espirituais têm sido um bálsamo para sua alma.Para cumprir com seus requisitos como pioneira, Natalia adota uma programação semanal meticulosa, equilibrando suas responsabilidades no campo com as demandas diárias da vida.O serviço pioneiro é para Natalia uma fonte de profunda felicidade e gratidão.  Ela reconhece o privilégio imerecido de servir nessa designação, lembrando-se dos quase 20 anos de esforço e ajustes necessários para chegar a esse ponto.  Em cada passo, ela sentiu a mão amorosa de Jeová guiando-a, lembrando-se com confiança das palavras reconfortantes de Isaías 41:10: 'Não tenha medo, pois estou com você.Não fique ansioso,pois eu sou o seu Deus.Vou fortalecê-lo, sim, vou ajudá-lo.Vou segurá-lo firmemente com a minha mão direita de justiça.'",
  },
  {
    id: 9,
    img: MariaImaculada,
    capa: capaMariaImaculada,
    nome: "Maria Imaculada",
    batismo: "1992",
    pioneiro: "2016 (serviço 4 anos antes)",
    title: "Vencendo a Timidez para uma Jornada Duradoura como Pioneira",
    biografia:
      "Maria Imaculada enfrentou desafios significativos ao decidir se tornar pioneira, especialmente devido à sua timidez inicial, o que tornava a pregação uma tarefa árdua.  No entanto, com determinação e superação, ela persistiu nesse serviço que hoje lhe proporciona imensas alegrias.Ao refletir sobre sua jornada, Maria Imaculada encontra inspiração no Cântico 80, destacando a alegria de dar o seu melhor a Jeová.  Para ela, o serviço pioneiro não é apenas um dever, mas uma fonte de propósito em sua vida.  A adoração a Jeová e a obediência aos Seus mandamentos são fundamentais para essa alegria, sabendo que Deus se alegra com seu esforço sincero.Maria Imaculada encontra felicidade em saber que o serviço pioneiro é um modo de expressar seu amor por Jeová e pelas pessoas ao seu redor.  Para cumprir com seus requisitos, ela estabelece arranjos específicos, inicia seu serviço cedo nas ruas e se dedica a escrever cartas.A experiência de ser pioneira é para Maria Imaculada uma fonte constante de felicidade, animação e gratidão.  Ela ama profundamente o privilégio de dedicar seu tempo e esforço a Jeová, sentindo-se verdadeiramente recompensada por esse trabalho gratificante.",
  },
  {
    id: 11,
    img: Andre,
    capa: capaAndre,
    nome: "André",
    batismo: "1999",
    pioneiro: "2016",
    title: "Conciliando Perdas e Alegrias: Uma Jornada Pioneira Excepcional",
    biografia:
      "Enfrentei alguns desafios como pioneira, incluindo a dor de perder pessoas queridas.  No entanto, consegui conciliar o serviço de pioneira com o trabalho secular em tempo integral, além de participar ativamente das atividades como ancião na congregação e cuidar da minha família.Apesar dos obstáculos enfrentados, ser pioneira me proporciona muitas alegrias, especialmente por ser uma ferramenta nas mãos de Jeová.  Testemunhar pessoas se aproximando do batismo e poder servir ao lado da minha esposa, e agora também com minha filha, são experiências inestimáveis.A alegria de ser pioneiro é algo indescritível e sem comparação.  Para atender aos requisitos do serviço pioneiro, criei uma programação semanal que envolve estudos noturnos e apoio ao campo nos finais de semana.",
  },
  {
    id: 12,
    img: Michelle,
    capa: capaMichelle,
    nome: "Michelle",
    batismo: "2007",
    pioneiro: "2023",
    title:
      "Conquistando o Pioneirismo: Uma Jornada de Superar Desafios Pessoais",
    biografia:
      "Michelle, além de ser mãe e esposa dedicada, desempenha um papel crucial no cuidado de seus sogros e de sua neta.  Sua jornada para se tornar pioneira foi marcada por desafios pessoais e sentimentos de insegurança, mas mesmo assim, ela tomou a decisão corajosa de dedicar-se plenamente ao serviço pioneiro.Enfrentando obstáculos pessoais, Michelle encontrou forças para superar suas inseguranças, tornando-se pioneira.  As alegrias que ela experimenta agora são inúmeras, especialmente ao contribuir ainda mais para Jeová, dedicando seu tempo e energia ao que considera o melhor trabalho existente.A experiência de ser pioneira despertou em Michelle um profundo sentimento de gratidão a Jeová.  Ela se considera privilegiada por ter a oportunidade de servir de maneira tão significativa.  Para cumprir seus requisitos, Michelle estabeleceu uma programação cuidadosa, contando com o apoio valioso de seu marido, filho e de muitas irmãs, que colaboram nos arranjos para as atividades.O comprometimento de Michelle como pioneira é um testemunho de sua resiliência, fé e alegria em servir a Jeová com amor e devoção.",
  },
  {
    id: 13,
    img: Sabrina,
    capa: capaSabrina,
    nome: "Sabrina",
    batismo: "2013",
    pioneiro: "2019 e 2024",
    title:
      "Alegria na Adversidade: Pioneirismo em Meio a Desafios Médicos e Pandemia",
    biografia:
      "A história de Sabrina é marcada por desafios significativos. Logo após assinar pela primeira vez, ela enfrentou uma situação difícil. Seu pai teve um problema médico que exigiu uma cirurgia crítica, ocorrendo no início da pandemia.  Durante esse período delicado, Sabrina, sua mãe e avó se revezaram para cuidar dele, enquanto sua mãe assumia a responsabilidade de sustentar a casa. Apesar desses desafios inesperados, Sabrina encontrou uma fonte genuína de alegria ao se tornar pioneira durante a pandemia.  Essa experiência permitiu que ela se conectasse com muitas pessoas, superando as dificuldades e compartilhando a mensagem de uma maneira que talvez nem imaginasse ser possível.Ser pioneira para Sabrina é mais do que um compromisso; é um sentimento profundo de alegria genuína e uma gratidão inexplicável por Jeová, que não apenas permitiu, mas também a ajudou a fazer mais para Ele, tanto no presente quanto no futuro.Sabrina estabeleceu uma programação cuidadosa para cumprir suas metas pioneiras.  Com um alvo de 12 horas semanais, ela procura realizar a maior parte de seu serviço nos primeiros dias da semana, considerando o aumento da ocupação no final.  Além disso, dedica-se a aprimorar suas habilidades de revisitas, reservando um dia específico para realizá-las. Sabrina também busca colaborar com as irmãs e apoiar seu grupo de domingo sempre que possível, demonstrando seu comprometimento constante com o serviço pioneiro.",
  },
  {
    id: 14,
    img: Severino,
    capa: capaSeverino,
    nome: "Severino",
    batismo: "1989",
    pioneiro: "2016",
    title: "Equilibrando Vida Secular, Familiar e Pioneirismo com Alegria",
    biografia:
      "Um dos desafios como pioneiro foi ter equilíbrio entre o trabalho secular, a família e o serviço para Jeová.  Apesar dos desafios, teve muitas alegrias, como ajudar um grupo de publicadores em outro estado e ver o resultado desse trabalho.  Ser pioneiro lhe dá uma alegria imensa e ajuda a ter mais associação com os irmãos.  Para cumprir o requisito, ele tem uma programação equilibrada com os dias de consulta.",
  },
  {
    id: 15,
    img: Isabel,
    capa: capaIsabel,
    nome: "Isabel",
    batismo: "1978",
    pioneiro: "2011",
    title: "Desafios e Alegrias: Uma Pioneira desde 1978",
    biografia:
      "Um dos desafios como pioneira era o serviço secular que exigia muito, o requisito de horas de 70, e o medo de não cumprir o que ser pioneira exigia.  Além disso, seu marido não era cristão e não entendia o que ela fazia como pioneira.  Mas as alegrias superaram os desafios, e ser pioneira a ajudou a aumentar sua relação com Jeová.  Ser pioneira lhe traz muita alegria, especialmente ao ajudar as pessoas a conhecerem a Jeová.  Para cumprir o requisito, ela faz uma programação semanal de acordo com suas folgas do serviço secular, que mudam a cada semana.",
  },
  {
    id: 16,
    img: Vitoria,
    capa: capaVitoria,
    nome: "Vitória",
    batismo: "2023",
    pioneiro: "2024",
    title: "Jovem Pioneira: Superando Dúvidas para Servir a Jeová",
    biografia:
      "Jovem em idade escolar.  Para ser pioneira, teve alguns desafios ao pensar que não iria cumprir com o requisito.  Ao tomar essa decisão, teve alguns questionamentos, mas tomou a decisão e sentiu a alegria de ver irmãos se colocando à disposição de ajudar.  Ela sente muita gratidão a Jeová por tê-la ajudado a realizar esse sonho e felicidade por poder fazer esse trabalho tão importante.  Para cumprir com seu serviço de pioneira, ela tenta se programar para fazer 2 horas por dia e assim também cumprir outras responsabilidades, como ajudar sua mãe, estudar tanto para Jeová quanto da escola, e preparar a reunião.",
  },
  {
    id: 17,
    img: Hugo,
    capa: capaHugo,
    nome: "Hugo",
    batismo: "2019",
    pioneiro: "2023",
    title: "Vencendo Desafios para Encontrar Alegria no serviçio de pioneiro",
    biografia:
      "Para servir como pioneiro, teve alguns desafios, como programações que nunca davam certo, o serviço que começou a sobrecarregá-lo e outros problemas como pressão no trabalho e ansiedade.  Mas teve muitas alegrias, como ver como Jeová nos ajuda a ter o necessário conforme damos de nós a ele.  Ser pioneiro não é só levar um título, mas sim levar o remédio para curar toda a doença deste mundo.  Ser usado por nosso criador como uma ferramenta de grande precisão e saber que nosso amoroso pai Jeová nos ajuda dá muita alegria e o motiva a continuar.  Ser pioneiro significa amar a Jeová, amar o próximo e ajudá-los.  Ele sente muita gratidão pelo serviço de pioneiro e acredita que pode gastar mais de si em prol do Reino ao participar ao máximo possível nas atividades.",
  },
  {
    id: 18,
    img: Stefany,
    capa: capaStefany,
    nome: "Stefany",
    batismo: "2013",
    pioneiro: "2024",
    title: "Uma Nova Fase: Jovem Pioneira Iniciando uma Jornada de Alegria",
    biografia:
      "Uma jovem que terminou sua fase escolar e está usando seu tempo para fazer mais para Jeová em algumas modalidades de serviço.  Acabou de tomar a decisão de ser pioneira, e para ela, agora é uma sensação de uma nova fase se iniciando.  Ela sente uma alegria incrível e considera o serviço de pioneira um esforço para fazer o que Jeová pede, ir atrás dos merecedores e ser mais aberta para ajudar outros na congregação.  O serviço é encorajador, e ela sente como algo que sempre esteve presente em sua vida.",
  },
  {
    id: 19,
    img: Alessandra,
    capa: capaAlessandra,
    nome: "Alessandra",
    batismo: "2008",
    pioneiro: "2009",
    title: "Alegrias Duradouras e Amizades no Pioneirismo Regular",
    biografia:
      "Um dos desafios como pioneira regular foi conciliar o serviço de pioneira com o serviço secular.  Mas conseguiu se manter no serviço e teve muitas alegrias, como fazer excelentes amizades que duram até hoje.  Para cumprir seu requisito, ela faz uma programação semanal e procura seguir sugestões de irmãs experientes com respeito ao ministério e aos arranjos.  Para ela, ser pioneira é maravilhoso, poder fazer parte de arranjos teocráticos que fortalecem sua relação com Jeová.",
  },
  {
    id: 20,
    img: Basilia,
    capa: capaBasilia,

    nome: "Basilia",
    batismo: "",
    pioneiro: "",
    title: "Desafiando Limitações: A Alegria de Ser Pioneira",
    biografia:
      "Um dos desafios como pioneira foi não saber escrever e responder algumas perguntas.  Mas, apesar disso, ser pioneira lhe trouxe muitas alegrias, como trabalhar com outras irmãs pioneiras nas reuniões de pioneira e na visita do superintendente.  Ela diz que ser pioneira dá muita alegria, não tem palavras para descrever.  Para cumprir o requisito, ela faz o seu melhor para ir no campo, no carrinho, testemunho informal e público na praça.",
  },
  {
    id: 21,
    img: Claudia,
    capa: capaClaudia,
    nome: "Claudia",
    batismo: "1999",
    pioneiro: "2008",
    title: "Alegria na Adversidade: Pioneirismo e Trabalho Secular",
    biografia:
      "Trabalha secularmente e também cuida de seu pai e mãe.  Para ela, o emprego secular sempre é um desafio, mas nunca deixou que isso atrapalhasse o seu desejo de ser pioneira.  Apesar dos desafios, ser pioneira dá muitas alegrias a ela, como se sentir mais próxima de Jeová e conseguir dirigir pelo menos um estudo onde alguém progrediu até o batismo.  Ser pioneira lhe dá alegria por poder dar de si numa obra tão importante.  Para cumprir com seu serviço de pioneira, ela procura fazer sempre ajustes para continuar, participando nas modalidades de pregação da congregação e seguindo as orientações para adaptações ao pregar.  Ela sente gratidão por essa modalidade ajudar a sempre achar uma maneira de fazer uma defesa do nome de Jeová de uma maneira constante.",
  },
  {
    id: 22,
    img: KellyCristina,
    capa: capaKellyCristina,
    nome: "Kelly Cristina",
    batismo: "1999",
    pioneiro: "2008",
    title: "Conciliando Família, Trabalho e Pioneirismo com Gratidão",
    biografia:
      "Trabalha secularmente e cuida de seus pais.  Para servir como pioneira, tinha alguns desafios, como conciliar trabalho secular, rotina doméstica e trabalho de tempo integral, além de um requisito de 70 horas.  Mas conseguiu conciliar esses desafios e se manteve no serviço, o que lhe deu muitas alegrias.  O serviço de pioneira a ajudou a se achegar e confiar mais em Jeová, vendo que Ele realmente ajuda a permanecer neste ministério.  Ela diz que, especialmente nesta pandemia, viu a mão de Jeová a ajudando, pois sem os ajustes que a organização fez para ajudar, não seria possível ter continuado, pelo menos por um tempo.  Ser pioneira é como sentir sua pele, faz parte dela, e ela se sente protegida, ocupada no ministério, sem tempo para coisas supérfluas que poderiam privar de Jeová.",
  },
  {
    id: 30,
    img: Samira,
    capa: capaSamira,
    nome: "Samira",
    batismo: "2017",
    pioneiro: "2023",
    title:
      "Jovem na Faculdade e Pioneira: Encontrando Felicidade na Adoração a Jeová",
    biografia:
      "Jovem terminou a fase escolar mas agora faz faculdade e trabalha.  Conseguindo conciliar seu tempo com o serviço de pioneira, o que lhe traz grande felicidade.  Ela diz que sente muito feliz de saber que está usando sua vida da melhor forma.  Procura fazer uma programação semanal para cumprir o requisito de horas.",
  },
  {
    id: 23,
    img: Flavia,
    capa: capaFlavia,
    nome: "Flavia",
    batismo: "1994",
    pioneiro: "2002",
    title:
      "Mãe, Dona de Casa e Pioneira: Alegria e Gratidão na Jornada Pioneira",
    biografia:
      "Mãe, dona de casa e esposa.  Um dos desafios no serviço foi logo no ano seguinte quando engravidou, e também quando o marido ficava desempregado era um grande desafio.  Mas teve muitas alegrias, como ajudar outros a adorar a Jeová, e hoje sua filha está no mesmo caminho.  O sentimento de ser pioneira para ela é alegria e gratidão, Jeová permitiu adorar a Ele.  Para cumprir o requisito, ela faz uma programação semanal.",
  },
  {
    id: 24,
    img: Emily,
    capa: capaEmily,
    nome: "Emily",
    batismo: "2020",
    pioneiro: "2023",
    title: "Saindo da Zona de Conforto: A Alegria de Ser Pioneira Regular",
    biografia:
      "Esposa dona de casa.  Quis ser pioneira regular para poder fazer mais para Jeová e sair da sua zona de conforto.  Ser pioneira dá muita alegria por estar lado a lado com os irmãos e podendo ajudar mais pessoas a aprender sobre Jeová.  Ela sente muita satisfação por poder fazer mais para Jeová.  Para cumprir com seu requisito, ela procura estar sempre no campo, no carrinho, apoiando as atividades e conta sempre com a ajuda de Jeová e das irmãs que a apoiam.",
  },
  {
    id: 25,
    img: Edileide,
    capa: capaEdileide,
    nome: "Edileide",
    batismo: "2020",
    pioneiro: "2023",
    title:
      "Pioneirismo com Cônjuge Descrente: A Alegria de Servir a Jeová Plenamente",
    biografia:
      "Esposa com cônjuge descrente.  Como seu marido não é cristão, teve que fazer alguns ajustes nos seus horários para poder se dedicar mais na pregação e estudos.  Ela sente uma alegria inesquecível de poder servir a Jeová plenamente como pioneira e poder sentir de perto o amor e cuidado de Jeová.  Ser Pioneira a deixa muito feliz por estar usando o seu tempo da melhor forma possível, se esforçando para ajudar as pessoas a conhecer a Jeová.  Para cumprir com sua programação, ela procura apoiar as atividades ministeriais, como campo, estudos e revistas, também apoiando as irmãs nas suas atividades durante a semana, e no sábado quando possível, visto que no fim de semana seu marido está em casa e ela fica com ele.",
  },

  {
    id: 26,
    img: Vania,
    capa: capaVania,
    nome: "Vania",
    batismo: "1998",
    pioneiro: "2009",
    title:
      "Persistência Pioneira ao Longo dos Anos: Superando Desafios com Alegria",
    biografia:
      "Um dos desafios foi o trabalho secular, e à noite ela ficou como pioneira por um tempo, depois parou, mas uns 4 anos depois em 2009 assinou novamente.  Durante esse tempo até agora, o desafio maior foi quando ela teve a filha Allana, porque com um bebê pequeno não dá para expor ela sempre no tempo, que às vezes está frio demais, chovendo ou sol demais.  Mas conseguiu se manter como pioneira, uma das ajudas foi com o requisito de horas reduzido.  Sente muita alegria em não ter desistido, compartilhar as verdades da Bíblia e estar sempre com os irmãos.  Para cumprir com seu requisito, ela faz uma programação semanal, aproveita bem os tempos quentes e tem a ajuda de seu marido para ficar com a filha enquanto ela vai em estudos e outras atividades.",
  },
  {
    id: 27,
    img: Amarildo,
    capa: capaAmarildo,
    nome: "Amarildo",
    batismo: "1999",
    pioneiro: "2014 (parou em 2018, voltou em 2023)",
    title: "Trabalho Integral e Pioneirismo: Superando Desafios com Alegria",
    biografia:
      "Trabalha em período integral, conciliando com o serviço de pioneiro.  Desafios superados com alegrias, como ajudar outros no caminho do batismo.  Alegria e apoio de Jeová no trabalho.  Programação inclui atividades durante a semana e aos finais de semana.",
  },
  {
    id: 28,
    img: Jeane,
    capa: capaJeane,
    nome: "Jeane",
    batismo: "2003",
    pioneiro: "2005",
    title:
      "Lidando com Desafios Iniciais e Sentindo o Amor de Jeová no Pioneirismo",
    biografia:
      "Jeane, como pioneira regular, enfrentou inicialmente o desafio da distância do território designado.Com o tempo, novos desafios surgiram, mas com a ajuda amorosa de Jeová e dos irmãos na fé, ela aprendeu a lidar com cada um deles.  Sua resiliência e confiança em Jeová a guiaram ao longo dessa jornada.Uma das maiores alegrias de Jeane é poder continuar no serviço pioneiro, mesmo reconhecendo suas próprias imperfeições.  Estar no serviço integralmente permite que ela sinta o amor de Jeová de maneira profunda.Além disso, experimentou a gratificação de ajudar alguns membros de sua família a aceitarem Jeová como seu Deus e Pai.Para Jeane, ser pioneira é uma proteção amorosa de Jeová e uma fonte constante de alegria ao colaborar com a congregação.  Mesmo com uma agenda intensa, trabalhando fora e enfrentando diversas atividades diárias, ela demonstra flexibilidade ao realizar suas tarefas pioneiras.  Reconhecendo as dificuldades realistas, Jeane esforça-se sempre para dar o seu melhor no serviço sagrado. Sua dedicação é um exemplo inspirador para todos ao seu redor.",
  },
  {
    id: 29,
    img: Capel,
    capa: capaCapel,
    nome: "Capel",
    batismo: "1997",
    pioneiro: "",
    title:
      "Casado, Servo e Pioneiro: Uma Jornada de Prazer no Serviço de Jeová",
    biografia:
      "Casado, servo no ministério e pioneiro regular.  Para ele, sempre foi um prazer servir como pioneiro.  Concilia trabalho secular com serviço no campo e atividades ministeriais.  Aproveita todas as oportunidades que surgem.",
  },
];
